title: Kris Veselits - GIS-Programming Portfolio # your name (or website title) here
logo: "/images/43455376 (3).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Assorted GIS Programming Projects showcasing Python Scripts, Tools, and Field Calculator examples, as well as JavaScript web-based maps.
  <br><br>
  <a href="https://www.linkedin.com/in/krisveselits">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
